### ISSUE TITLE
형변환, 포인터, 함수에 대해 알아보자

### ISSUE THREAD

**Issue by HoonyCode** [knu-of/c-study#2]
## 목표
형변환, 포인터, 함수에 대해 알아보자

## 학습할 것
- 형변환 (타입 캐스팅)
- 포인터
- 함수

## 스터디 일시
2021년 10월 03일 오후 6시

**Comment by HoonyCode** [comment]
https://github.com/HoonyCode/c-study/blob/master/2%EC%A3%BC%EC%B0%A8/2.md

**Comment by KeiEsem** [comment]
https://keiesem.tistory.com/3

**Comment by sohee0814** [comment]
[형변환, 포인터, 함수.pptx](https://github.com/knu-of/c-study/files/7272932/default.pptx)

**Comment by sohee0814** [comment]
[형변환, 포인터, 함수.pptx](https://github.com/knu-of/c-study/files/7272936/default.pptx)

**Comment by koseungju** [comment]
[c프로그래밍(포인터, 형변환, 함수).pdf](https://github.com/knu-of/c-study/files/7272947/c.pdf)

**Comment by HWAN-CHUL-LA** [comment]
https://made-by-c.tistory.com/2
