### ISSUE TITLE
구조체에 대해서 알아보자

### ISSUE THREAD

**Issue by HoonyCode** [knu-of/c-study#3]
## 목표
구조체에 대해서 알아보자

## 학습할 것
- 구조체란?
- 구조체 장점
- 구조체를 정의하는 방법
- 공용체(union)이란
- 열거형(enum)이란

# 숙제
- 별찍기 두 문제
- 구조체`struct`를 이용해서 정보를 받고 출력하기

```C
// 구조체 예
struct person{
    int age;
    char name[10];
    char address[30];
    char self_introduce[100];
}
```
## 스터디 일시
2021년 10월 08일 오후 6시

**Comment by HoonyCode** [comment]
https://github.com/HoonyCode/c-study/blob/master/3%EC%A3%BC%EC%B0%A8/3%EC%A3%BC%EC%B0%A8.md

**Comment by sohee0814** [comment]
[구조체.pptx](https://github.com/knu-of/c-study/files/7309512/default.pptx)

**Comment by HWAN-CHUL-LA** [comment]
https://made-by-c.tistory.com/3

**Comment by koseungju** [comment]
[구조체.docx](https://github.com/knu-of/c-study/files/7316907/default.docx)
