### ISSUE TITLE
동적할당에 대해서 알아보자

### ISSUE THREAD

**Issue by HoonyCode** [knu-of/c-study#4]
## 목표
동적할당에 대해서 알아보자

## 학습할 것
- 동적할당이란 무엇인가?
- 동적할당의 장점
- 동적할당의 단점
- 동적할당 정의하는 법
- 1차원 배열의 할당
- 2차원 배열의 할당
- malloc, realloc, calloc의 비교

# 숙제
- https://www.acmicpc.net/step/1 있는 문제 다 풀어오기

## 스터디 일시
2021년 10월 10일 오후 1시

**Comment by HoonyCode** [comment]
https://github.com/HoonyCode/c-study/blob/master/part4.md

**Comment by HWAN-CHUL-LA** [comment]
https://made-by-c.tistory.com/4

**Comment by sohee0814** [comment]
[동적할당.pptx](https://github.com/knu-of/c-study/files/7316794/default.pptx)

**Comment by koseungju** [comment]
[동적할당.docx](https://github.com/knu-of/c-study/files/7352145/default.docx)
